apiVersion: v1
kind: Service
metadata:
  name: hazelcast-ee
  labels:
    app: hazelcast-ee
spec:
  type: NodePort
  selector:
    app: hazelcast-ee
  ports:
  - protocol: TCP
    port: 5701
    name: hzport

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: hazelcast-ee
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hazelcast-ee
    spec:
      containers:
      - name: hazelcast-ee-node
        image: hazelcast/hazelcast-enterprise-kubernetes:3.9.1
        ports:
        - containerPort: 5701
        livenessProbe:
          exec:
            command:
            - "./liveness.sh"
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: hz-ee-config
        env:
        - name: HZ_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              name: hz-ee-license
              key: key
