general:
  vulnerabilities:
    # netty-tcnative still requires libssl 1.0
    - CVE-2019-1543
    - CVE-2020-1967
  bestPracticeViolations:
    # HZ_LICENSE_KEY included as an env variable
    - CIS-DI-0010
    # We don't sign Hazelcast Docker images
    - CIS-DI-0005
