version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/hazelcast-oss"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/hazelcast-enterprise"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      # https://github.com/dependabot/dependabot-core/issues/6345#issuecomment-3376986288
      - "/.github/actions/*"
    target-branch: "master"
    schedule:
      interval: "daily"
