= Hazelcast Openshift Enterprise Integration
Hazecast Inc, Integrations Team <https://github.com/hazelcast>
// Settings:
:compat-mode!:
:idseperator: -
// Aliases:
:project-name: Hazelcast Openshift Enterprise Integration
:project-handle: hazelcast-openshift-rhel
:toc:

This directory contains all files to produce a Hazelcast Docker image based on Red Hat Enterprise Linux 7 (RHEL7), which security rules set to work on Openshift Enterprise deployments (hosted, on-premise).

Openshift Enterprise itself builts atop Kubernetes and Docker, therefore the link:https://github.com/hazelcast/hazelcast-kubernetes[Hazelcast Kubernetes Discovery] plugin is used to find other nodes inside the Openshift environment.

== Installation of the Hazelcast Template

The easiest way to install the Hazelcast template into Openshift is to SSH into the Openshift master. It can also be done remotely by installing the Openshift CLI tools or Red Hat JBoss Developer Studio, but both way require way more setup steps.

After logging into Openshift master via SSH, the template has to be installed using the oc shell command provided by Openshift.

To login into the CLI administration of Openshift use:

```
oc login https://localhost:8443
```

Default username and password is "admin" (at least on Openshift Origin), might be different depending on the Openshift installation. The user should have admin rights though.

The template is installed per project. To create a new project execute the following command (can also be done using the Openshift Web UI) and switch into the newly created project:

```
oc new-project ${project-name}
oc project ${project-name}
```

Copy the `hazelcast-template.js` file (for example with scp) over to the Openshift master and install it into a (new) project using the following chain of commands.

```
oc create -f hazelcast-template.js -n ${project-name}
```

This template file contains all the deployment information to setup a Hazelcast cluster from inside Openshift. It configures the necessary ReplicationController, healthchecks and image to use. It also offers a set of properties to be requested when creating a new cluster (such as clustername).

== Creation of a Hazelcast cluster

The creation of a Hazelcast cluster in Openshift Enterprise is a simple process. After logging into the Web UI (https://${openshift-server}:8433/admin) with credentials to create new deployments inside the previously created project.

Select the interesting project from the dropdown box, if not automatically selected, and click "Add to Project" button. In the textfield search for "hazelcast" and select the "hazelcast-openshift-rhel" template.

The next screen asks for configuration properties for this specific for the current deployment. `DEPLOYMENT_NAME` and `SERVICE_NAME` are required to fill. For information about the different properties, see description below.

A final click on "Create" will create the cluster. By default 3 nodes are created. The number can be scaled up and down using the ReplicationController.

== Configuration properties

The Hazelcast deployment template (hazelcast-template.js) contains a set of properties to be set when creating a Hazelcast cluster.

=== DEPLOYMENT_NAME

Defines the name of the new cluster, the so called  deployment unit. All created resources are named according to this base name, therefore the value is required.

=== SERVICE_NAME

Defines the service name inside Kubernetes and the label for the PODs (the actual virtual container instances). This property is required.

=== NAMESPACE

Defines the Kubernetes name of the Openshift project which must match the project name. This property is not required. If not provided the `start.sh` will read the value from `/var/run/secrets/kubernetes.io/serviceaccount/namespace` on startup of the container.

=== KUBERNETES_SERVICE_DOMAIN

Defines the domain part of the kubernetes DNS lookup and defaults to "cluster.local" which is ok in most cases and should only be changed when there is some special configuration on the Kubernetes DNS service.
