name: 'Update Docker Hub README'
description: 'Composite action to update Docker Hub README for OSS and EE images'
inputs:
  docker_username:
    description: 'Docker username'
    required: true
  docker_password:
    description: 'Docker password'
    required: true

runs:
  strategy:
    matrix:
      include:
        - repository: hazelcast/hazelcast
          short-description: Hazelcast Docker Image
        - repository: hazelcast/hazelcast-enterprise
          short-description: Hazelcast Enterprise Docker Image

  using: 'composite'
  steps:
    - name: Generate Docker Hub Description
      shell: bash
      run: |
        .github/scripts/generate-docker-hub-description.sh

    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}
        repository: ${{ matrix.repository }}
        short-description: ${{ matrix.short-description }}
        readme-filepath: ./README-docker.md