general:
  vulnerabilities:
    # ubi-minimal marked as WONTFIX
    - CVE-2019-1010022
    - CVE-2019-5827
  bestPracticeViolations:
    # HZ_LICENSE_KEY included as an env variable
    - CIS-DI-0010
    # We don't sign Hazelcast Docker images
    - CIS-DI-0005
