name: Check RedHat Service Status
runs:
  using: "composite"
  steps:
    - name: Check RedHat status
      shell: bash
      run: |
        # shellcheck source=logging.functions.sh
        . ${{ github.action_path }}/logging.functions.sh

        # https://status.redhat.com/api
        STATUS=$(curl --silent https://status.redhat.com/api/v2/status.json)

        if jq --exit-status '.status.indicator != "none"' <<< "${STATUS}"; then
          echoerr "❌ RedHat service status"
          echoerr "$(jq '.status' <<< ${STATUS})"
          echoerr "$(curl --silent https://status.redhat.com/api/v2/incidents/unresolved.json | jq)"
          exit 1
        fi
