name: Derive versions
description: Calculates appropriate HZ_VERSION and RELEASE_VERSION
inputs:
  hz_version:
    description: 'Version of Hazelcast to build the image for, e.g. 5.1.1, 5.0.1'
    required: false
  release_version:
    description: 'Version to tag the docker image e.g. 5.1.1, 5.1.1-1, defaults to HZ_VERSION'
    required: false
outputs:
  hz_version:
    value: ${{ steps.set_hz_version.outputs.HZ_VERSION }}
  release_version:
    value: ${{ steps.set_release_version.outputs.RELEASE_VERSION }}
runs:
  using: composite
  steps:
    - name: Set HZ version
      shell: bash
      id: set_hz_version
      run: |
        if [ -n "${{ inputs.HZ_VERSION }}" ]; then
          echo "HZ_VERSION=${{ inputs.HZ_VERSION }}" >> ${GITHUB_OUTPUT}
        else
          echo "HZ_VERSION=${GITHUB_REF:11}" >> ${GITHUB_OUTPUT}
        fi

    - name: Set Release version
      shell: bash
      id: set_release_version
      run: |
        if [ -n "${{ inputs.RELEASE_VERSION }}" ]; then
            echo "RELEASE_VERSION=${{ inputs.RELEASE_VERSION }}" >> ${GITHUB_OUTPUT}
        else
            echo "RELEASE_VERSION=${{ steps.set_hz_version.outputs.HZ_VERSION }}" >> ${GITHUB_OUTPUT}
        fi
