name: Get tag name from branch

inputs:
  SOURCE_REF:
    required: true
outputs:
  TAG_NAME:
    value: v${{ inputs.SOURCE_REF }}
runs:
  using: "composite"
  steps:
    - shell: bash
      run: exit 0
