name: Setup Docker
inputs:
  platforms:
    description: Platforms to install (e.g., `arm64,riscv64,arm`)
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.platforms }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # Workaround "dial tcp: lookup registry on {ip}: no such host"
        # See example - https://docs.docker.com/build/ci/github-actions/local-registry/
        driver-opts: network=host
