name: Setup Docker
inputs:
  platforms:
    description: Platforms to install (e.g., `arm64,riscv64,arm`)
    required: true
runs:
  using: "composite"
  steps:
    # Default GitHub runners have very little free disk space causing build failures
    - name: Free Disk Space
      # https://github.com/jlumbroso/free-disk-space/releases/tag/v1.3.1
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
      with:
        docker-images: false

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.platforms }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # Workaround "dial tcp: lookup registry on {ip}: no such host"
        # See example - https://docs.docker.com/build/ci/github-actions/local-registry/
        driver-opts: network=host
