name: Check base images

on:
  workflow_dispatch:
    inputs:
      MINIMAL_SUPPORTED_VERSION:
        description: 'Minimal supported version from which we should start checking images, e.g. 5.1, 5.0.1, 4.2.3. Default derived from supported maintenance versions'
        required: false
  schedule:
    - cron: '0 6 * * *'

jobs:
  get-latest-patch-versions:
    runs-on: ubuntu-latest
    name: Get latest patch versions
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    env:
      MINIMAL_SUPPORTED_VERSION: ${{ inputs.MINIMAL_SUPPORTED_VERSION }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: get-maintenance-versions
        uses: hazelcast/hazelcast/.github/actions/get-supported-maintenance-versions@master
      - name: Calculate minimal supported version
        run: echo "DEFAULT_MINIMAL_SUPPORTED_VERSION=$(echo '${{ steps.get-maintenance-versions.outputs.versions }}' | jq '.[0]')" >> $GITHUB_ENV
      - id: set-matrix
        name: Get latest patch versions
        run: |
          . .github/scripts/version.functions.sh
          MIN_VERSION=${MINIMAL_SUPPORTED_VERSION:-$DEFAULT_MINIMAL_SUPPORTED_VERSION}
          echo "Getting latest patch versions starting from $MIN_VERSION"
          versions=$(printf '%s\n' $(get_latest_patch_versions "${MIN_VERSION}") | jq --raw-input . | jq --compact-output --slurp .)
          echo "Found latest patch versions: $versions"
          echo "matrix={\"version\":$versions}" >> $GITHUB_OUTPUT

  calculate-rebuilds:
    runs-on: ubuntu-latest
    name: Calculate if ${{ matrix.version }} needs a rebuild
    needs: get-latest-patch-versions
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.get-latest-patch-versions.outputs.matrix) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Checkout version ${{ matrix.version }}
        uses: actions/checkout@v5
        with:
          ref: v${{ matrix.version }}
          path: v${{ matrix.version }}
      - name: Check if ${{ matrix.version }} base images updated
        run: |
          set -x

          . .github/scripts/base-image-updated.functions.sh
          . .github/scripts/packages-updated.functions.sh
          . .github/scripts/logging.functions.sh

          check_image() {
            local label=$1
            local image=$2
            local dockerfile=$3

            echo "Checking ${label} image"
            if base_image_outdated_from_dockerfile "${image}" "${dockerfile}"; then
              echo "${{ matrix.version }}" >> rebuild-${label}-${{ matrix.version }}
              echonotice "Image ${label} needs rebuild"
            elif packages_updatable_ee "${image}"; then
              echo "${{ matrix.version }}" >> rebuild-${label}-${{ matrix.version }}
              echonotice "System package upgrades for ${label} image available"
            else
              echodebug "Image ${label} is up-to-date"
            fi
          }

          check_image "EE" "hazelcast/hazelcast-enterprise:${{ matrix.version }}-slim" "v${{ matrix.version }}/hazelcast-enterprise/Dockerfile"
        # GitHub doesn't support outputs of matrix jobs - https://github.com/orgs/community/discussions/26639
        # Instead, write the content to artifact(s) and upload those to consume downstream
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}
          path: rebuild-*
          if-no-files-found: ignore
