name: Redhat status test
# Entry point to debug the `check-redhat-service-status` action

on:
  workflow_dispatch:

jobs:
  service-status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/check-redhat-service-status
