name: Redhat status test
# Entry point to debug the `check-redhat-service-status` action

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-redhat-service-status
