name: Redhat status test
# Entry point to debug the `check-redhat-service-status` action
# Doesn't have to be reusable as it's triggered only from master branch

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/check-redhat-service-status
