name: Promote EE NLC image from pre-prod to prod

on:
  # For debugging only
  workflow_dispatch:
    inputs:
      SOURCE_REF:
        description: 'The hazelcast-docker branch to promote'
        required: true
      HZ_REVISION:
        description: 'Commit id of Hazelcast snapshot jar'
        required: false
      ENVIRONMENT:
        description: 'Environment to use'
        required: true
        type: environment
  workflow_call:
    inputs:
      SOURCE_REF:
        description: 'The hazelcast-docker branch to promote'
        required: true
        type: string
      HZ_REVISION:
        description: 'Commit id of Hazelcast snapshot jar'
        required: false
        type: string
      ENVIRONMENT:
        description: 'Environment to use'
        required: true
        type: string

jobs:
  prepare:
    uses: ./.github/workflows/tag_image_prepare.yml
    with:
      SOURCE_REF: ${{ inputs.SOURCE_REF }}
      RELEASE_TYPE: EE
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}

  promote-nlc:
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        jdk: ${{ fromJSON(needs.prepare.outputs.jdks) }}
    env:
      LOCAL_IMAGE_NAME: localhost:5000/${{ vars.NLC_IMAGE_NAME }}
    services:
      registry:
        image: registry:latest
        ports:
          - 5000:5000
    steps:
      - uses: actions/checkout@v7

      - id: get-tags-to-push
        uses: ./.github/actions/get-tags-to-push-nlc
        with:
          hz-version: ${{ needs.prepare.outputs.hz-version }}
          jdk: ${{ matrix.jdk }}
          default-jdk: ${{ needs.prepare.outputs.default-jdk }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_DEV_INFRA_OIDC_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: 'us-east-1'

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v3
        with:
          secret-ids: |
            NLC/IMAGE_REGISTRY
          parse-json-secrets: true

      - name: Login to NLC registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.NLC_IMAGE_REGISTRY_URL }}
          username: ${{ env.NLC_IMAGE_REGISTRY_USERNAME }}
          password: ${{ env.NLC_IMAGE_REGISTRY_TOKEN }}

      - name: Push image to remote registry
        run: |
          do
            skopeo copy \
              --all \
              --retry-times 10 \
              docker://${NLC_IMAGE_REGISTRY_URL}/hazelcast_cloud/${{ vars.NLC_IMAGE_NAME }}-${{ vars.PREPROD_REGISTRY }}:${{ steps.get-tags-to-push.outputs.primary-tag }} \
              docker://${NLC_IMAGE_REGISTRY_URL}/hazelcast_cloud/${{ vars.NLC_IMAGE_NAME }}:${tag}
          done
        env:
          TAGS_TO_PUSH: ${{ steps.get-tags-to-push.outputs.all-destination-tags }}

      - uses: sigstore/cosign-installer@6f9f17788090df1f26f669e9d70d6ae9567deba6 # v4.1.2

      - name: Validate image signature
        timeout-minutes: 1
        run: |
          source /dev/stdin <<< "$(curl --fail --retry 5 --retry-all-errors --show-error --silent https://raw.githubusercontent.com/hazelcast/github-actions-common-scripts/main/logging.functions.sh)"

          # https://github.com/sigstore/cosign-installer#usage
          # Image signatures can take a couple of seconds to appear after the main image (suspect "oras cp --recursive" is not fully atomic), so poll for completion
          while ! cosign verify \
            --certificate-identity-regexp "${GITHUB_SERVER_URL//./\\.}/${GITHUB_REPOSITORY}/.*" \
            --certificate-oidc-issuer https://token.actions.githubusercontent.com \
            ${NLC_IMAGE_REGISTRY_URL}/hazelcast_cloud/${{ vars.NLC_IMAGE_NAME }}:${{ steps.get-tags-to-push.outputs.primary-tag }}; do
              echodebug "Signature verification failed - additional annotations may not yet be available, retrying..."
              sleep 1
          done

      - name: Check RedHat service status
        if: failure()
        uses: hazelcast/docker-actions/check-redhat-service-status@master

  failure-notifications:
    name: Failure notification
    if: failure() && github.triggering_actor == 'devOpsHazelcast'
    needs: promote-nlc
    uses: ./.github/workflows/slack-notification.yml
    secrets: inherit
