name: Get distribution variants

on:
  workflow_call:
    outputs:
      variants:
        value: ${{ jobs.get-distribution-variants.outputs.variants }}

jobs:
  get-distribution-variants:
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.get-matrix.outputs.variants }}
    steps:
      - id: get-matrix
        run: |
          echo "variants=[{'classifier':'slim','suffix':'-slim'},{'classifier':'','suffix':''}]" >> ${GITHUB_OUTPUT}
