name: Get distribution variants

on:
  workflow_call:
    outputs:
      variants:
        value: ${{ jobs.get-distribution-variants.outputs.variants }}

jobs:
  get-distribution-variants:
    runs-on: ubuntu-latest
    outputs:
      variants: ${{ steps.get-matrix.outputs.variants }}
    steps:
      - id: get-matrix
        run: |
          echo "variants=$(jq --null-input --compact-output '["slim", ""] | map({ classifier: ., suffix: (if . == "" then "" else "-\(.)" end) })')" >> ${GITHUB_OUTPUT}