name: Push EE RHEL image

on:
  workflow_dispatch:
jobs:
  build:
    environment: live
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Red Hat Scan Registry
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: redhat-isv-containers+${{ secrets.RHEL_PROJECT_ID_V5 }}-robot
          password: ${{ secrets.SCAN_REGISTRY_PASSWORD_V5 }}

      - name: Install `preflight` OpenShift tool from GitHub
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          preflight: "latest"
          source: github
          skip_cache: true

      - name: Run preflight scan
        run: |
          preflight check container "quay.io/redhat-isv-containers/${{ secrets.RHEL_PROJECT_ID_V5 }}:5.4.3-jdk21" \
            --submit --pyxis-api-token=${{ secrets.RHEL_API_KEY }} \
            --certification-component-id=${{ secrets.RHEL_PROJECT_ID_V5 }} \
            --docker-config ~/.docker/config.json
