name: GH Test

on:
  pull_request:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Management Center Version to be used in the tests
        run: |
          gh api repos/hazelcast/management-center/tags
        env:
          GH_TOKEN: ${{ github.token }}
