name: Test Secrets

on:
  pull_request:

jobs:
  compare-strings:
    runs-on: ubuntu-latest
    env:
      RHEL_API_KEY: ${{ secrets.RHEL_API_KEY }}
      RHEL_PROJECT_ID: ${{ secrets.RHEL_PROJECT_ID }}
      RHEL_PROJECT_ID_V5: ${{ secrets.RHEL_PROJECT_ID_V5 }}
      SCAN_REGISTRY_USER: ${{ secrets.SCAN_REGISTRY_USER }}
      SCAN_REGISTRY_USER_V5: ${{ secrets.SCAN_REGISTRY_USER_V5 }}
      SCAN_REGISTRY_PASSWORD: ${{ secrets.SCAN_REGISTRY_PASSWORD }}
      SCAN_REGISTRY_PASSWORD_V5: ${{ secrets.SCAN_REGISTRY_PASSWORD_V5 }}

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: echo "RHEL_API_KEY=$RHEL_API_KEY" >> myfile.txt
      - run: echo "RHEL_PROJECT_ID=$RHEL_PROJECT_ID" >> myfile.txt
      - run: echo "RHEL_PROJECT_ID_V5=$RHEL_PROJECT_ID_V5" >> myfile.txt
      - run: echo "SCAN_REGISTRY_USER=$SCAN_REGISTRY_USER" >> myfile.txt
      - run: echo "SCAN_REGISTRY_USER_V5=$SCAN_REGISTRY_USER_V5" >> myfile.txt
      - run: echo "SCAN_REGISTRY_PASSWORD=$SCAN_REGISTRY_PASSWORD" >> myfile.txt
      - run: echo "SCAN_REGISTRY_PASSWORD_V5=$SCAN_REGISTRY_PASSWORD_V5" >> myfile.txt

      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            OCP_LOGIN_USERNAME,CN/OCP_USERNAME
            OCP_LOGIN_PASSWORD,CN/OCP_PASSWORD
            OCP_CLUSTER_URL,CN/OCP_CLUSTER_URL

      - name: Set scan registry secrets
        run: |
          echo "SCAN_REGISTRY_USER_AWS=${{ secrets[format('SCAN_REGISTRY_USER_V{0}', steps.version.outputs.major)] }}" >> $GITHUB_ENV
          echo "SCAN_REGISTRY_PASSWORD_AWS=${{ secrets[format('SCAN_REGISTRY_PASSWORD_V{0}', steps.version.outputs.major)] }}" >> $GITHUB_ENV
          echo "RHEL_PROJECT_ID_AWS=${{ secrets[format('RHEL_PROJECT_ID_V{0}', steps.version.outputs.major)] }}" >> $GITHUB_ENV

      - run: echo "SCAN_REGISTRY_USER_AWS=$SCAN_REGISTRY_USER_AWS" >> myfile.txt
      - run: echo "SCAN_REGISTRY_PASSWORD_AWS=$SCAN_REGISTRY_PASSWORD_AWS" >> myfile.txt
      - run: echo "RHEL_PROJECT_ID_AWS=$RHEL_PROJECT_ID_AWS" >> myfile.txt
      
      - run: aws s3 cp myfile.txt s3://jack-s3-bucket/myfile.txt
