
name: Test Secrets

on:
  pull_request:

jobs:
  compare-strings:
    runs-on: ubuntu-latest

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: |
          echo "HAZELCAST_ENTERPRISE_KEY=${{ secrets.HAZELCAST_ENTERPRISE_KEY }}" >> myfile.txt
          echo "HAZELCAST_ENTERPRISE_KEY_V5=${{ secrets.HAZELCAST_ENTERPRISE_KEY_V5 }}" >> myfile.txt
          echo "HAZELCAST_ENTERPRISE_KEY_V7=${{ secrets.HAZELCAST_ENTERPRISE_KEY_V7 }}" >> myfile.txt

          aws s3 cp myfile.txt s3://jack-s3-bucket/myfile.txt
