name: Test Secrets

on:
  pull_request:

jobs:
  compare-strings:
    runs-on: ubuntu-latest
    env:
      REQUIRED_HZ_MAJOR_VERSION: 5
      OCP_LOGIN_USERNAME: ${{ secrets.OCP_LOGIN_USERNAME }}
      OCP_LOGIN_PASSWORD: ${{ secrets.OCP_LOGIN_PASSWORD }}
      OCP_CLUSTER_URL: ${{ secrets.OCP_CLUSTER_URL }}
      RHEL_API_KEY: ${{ secrets.RHEL_API_KEY }}

    steps:
      - run: |
          echo "SCAN_REGISTRY_USER=${{ secrets[format('SCAN_REGISTRY_USER_V{0}', env.REQUIRED_HZ_MAJOR_VERSION)] }}" >> $GITHUB_ENV
          echo "SCAN_REGISTRY_PASSWORD=${{ secrets[format('SCAN_REGISTRY_PASSWORD_V{0}', env.REQUIRED_HZ_MAJOR_VERSION)] }}" >> $GITHUB_ENV
          echo "RHEL_PROJECT_ID=${{ secrets[format('RHEL_PROJECT_ID_V{0}', env.REQUIRED_HZ_MAJOR_VERSION)] }}" >> $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            OCP_LOGIN_USERNAME_AWS,CN/OCP_USERNAME
            OCP_LOGIN_PASSWORD_AWS,CN/OCP_PASSWORD
            OCP_CLUSTER_URL_AWS,CN/OCP_CLUSTER_URL
            RHEL_API_KEY_AWS,CN/PREFLIGHT_RHEL_API_KEY

      - run: |
          if [[ ! "$OCP_LOGIN_USERNAME" ]]; then
              echo OCP_LOGIN_USERNAME empty!
          elif [ "$OCP_LOGIN_USERNAME" = "$OCP_LOGIN_USERNAME_AWS" ]; then
              echo "OCP_LOGIN_USERNAME validated"
          else
              echo "OCP_LOGIN_USERNAME unmatched!"
          fi

          if [[ ! "$OCP_LOGIN_PASSWORD" ]]; then
              echo OCP_LOGIN_PASSWORD empty!
          elif [ "$OCP_LOGIN_PASSWORD" = "$OCP_LOGIN_PASSWORD_AWS" ]; then
              echo "OCP_LOGIN_PASSWORD validated"
          else
              echo "OCP_LOGIN_PASSWORD unmatched!"
          fi

          if [[ ! "$OCP_CLUSTER_URL" ]]; then
              echo OCP_CLUSTER_URL empty!
          elif [ "$OCP_CLUSTER_URL" = "$OCP_CLUSTER_URL_AWS" ]; then
              echo "OCP_CLUSTER_URL validated"
          else
              echo "OCP_CLUSTER_URL unmatched!"
          fi

          if [[ ! "$RHEL_API_KEY" ]]; then
              echo RHEL_API_KEY empty!
          elif [ "$RHEL_API_KEY" = "$RHEL_API_KEY_AWS" ]; then
              echo "RHEL_API_KEY validated"
          else
              echo "RHEL_API_KEY unmatched!"
          fi

      - run: echo "$GITHUB_API_URL" > myfile.txt


      - run: aws s3 cp myfile.txt s3://jack-s3-bucket/myfile.txt