name: Test Secret Masking
on:
  pull_request:

    branches:
      - 'master'

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output: ${{ steps.set-matrix.outputs.output }}
    steps:
    - uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ secrets.AWS_DEV_INFRA_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_DEV_INFRA_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          JFROG/READONLY_DEV_ACCOUNT
        parse-json-secrets: true

    - run: printenv

    - id: set-matrix
      run: echo "output=${JFROG_READONLY_DEV_ACCOUNT_USERNAME}.to" >> $GITHUB_OUTPUT

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - run: curl -s -w "%{http_code}" https://${{ needs.job1.outputs.output }}
