name: Test Secrets

on:
  pull_request:

jobs:
  compare-strings:
    runs-on: ubuntu-latest
    env:
      REQUIRED_HZ_MAJOR_VERSION: 5
      OCP_LOGIN_USERNAME: ${{ secrets.OCP_LOGIN_USERNAME }}
      OCP_LOGIN_PASSWORD: ${{ secrets.OCP_LOGIN_PASSWORD }}
      OCP_CLUSTER_URL: ${{ secrets.OCP_CLUSTER_URL }}
      RHEL_API_KEY: ${{ secrets.RHEL_API_KEY }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            OCP_LOGIN_USERNAME_AWS,CN/OCP_USERNAME
            OCP_LOGIN_PASSWORD_AWS,CN/OCP_PASSWORD
            RHEL_API_KEY_AWS,CN/PREFLIGHT_RHEL_API_KEY

      - name: Compare multiple string pairs
        run: |
          if [[ ! "$OCP_LOGIN_USERNAME" ]]; then
              echo OCP_LOGIN_USERNAME empty!
              exit 1
          elif [ "$OCP_LOGIN_USERNAME" = "$OCP_LOGIN_USERNAME_AWS" ]; then
              echo "OCP_LOGIN_USERNAME validated"
          else
              echo "OCP_LOGIN_USERNAME unmatched!"
              exit 1
          fi

          if [[ ! "$OCP_LOGIN_PASSWORD" ]]; then
              echo OCP_LOGIN_PASSWORD empty!
              exit 1
          elif [ "$OCP_LOGIN_PASSWORD" = "$OCP_LOGIN_PASSWORD_AWS" ]; then
              echo "OCP_LOGIN_PASSWORD validated"
          else
              echo "OCP_LOGIN_PASSWORD unmatched!"
              exit 1
          fi

          if [[ ! "$RHEL_API_KEY" ]]; then
              echo RHEL_API_KEY empty!
              exit 1
          elif [ "$RHEL_API_KEY" = "$RHEL_API_KEY_AWS" ]; then
              echo "RHEL_API_KEY validated"
          else
              echo "RHEL_API_KEY unmatched!"
              exit 1
          fi
