name: 3.12.z Vulnerability Scan

on:
  push:
    branches:
      - 3.12.z

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build OSS image
        run: |
          docker build -t hazelcast/oss:${{ github.sha }} hazelcast-oss
      - name: Build EE image
        run: |
          docker build -t hazelcast/ee:${{ github.sha }} hazelcast-enterprise
      - name: Scan OSS image by Azure (Trivy + Dockle)
        uses: Azure/container-scan@v0
        with:
          image-name: hazelcast/oss:${{ github.sha }}
          severity-threshold: MEDIUM

      - name: Scan OSS image by Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: hazelcast/oss:${{ github.sha }}
          args: --file=hazelcast-oss/Dockerfile --policy-path=.github/containerscan --severity-threshold=medium

      - name: Scan EE image by Azure (Trivy + Dockle)
        uses: Azure/container-scan@v0
        with:
          image-name: hazelcast/ee:${{ github.sha }}
          severity-threshold: MEDIUM

      - name: Scan EE image by Snyk
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: hazelcast/ee:${{ github.sha }}
          args: --file=hazelcast-enterprise/Dockerfile --policy-path=.github/containerscan --severity-threshold=medium