apiVersion: v1
kind: Service
metadata:
  name: hazelcast
  labels:
    app: hazelcast
spec:
  type: NodePort
  selector:
    app: hazelcast
  ports:
  - protocol: TCP
    port: 5701
    name: hzport

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: hazelcast
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hazelcast
    spec:
      containers:
      - name: hazelcast-node
        image: hazelcast/hazelcast-kubernetes:3.10-BETA-1
        ports:
        - containerPort: 5701
        livenessProbe:
          exec:
            command:
            - "./liveness.sh"
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: hz-config
